CREATE TABLE restaurants (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(120)  NOT NULL,
    description TEXT,
    category    VARCHAR(60),
    rating      DECIMAL(2,1),
    address     TEXT,
    image_url   TEXT,
    is_open     BOOLEAN DEFAULT true,
    created_at  TIMESTAMPTZ DEFAULT now()
);

INSERT INTO restaurants (name, description, category, rating, address, is_open)
VALUES
  ('La Parrilla de Juan', 'Carnes a la brasa', 'Parrilla', 4.7, 'Av. 18 de Julio 1234', true),
  ('Sushi Montevideo',    'Fusión japonesa',   'Japonés',  4.5, 'Pocitos 567', true),
  ('El Horno',           'Pizzas artesanales', 'Pizza',    4.3, 'Cordón 890', false),
  ('Parrilla Central', 'Carnes premium', 'Parrilla', 4.6, 'Centro 101', true),
  ('Pizza Sur', 'Pizzas caseras', 'Pizza', 4.2, 'Cordón 202', true),
  ('Sushi Go', 'Sushi rápido', 'Japonés', 4.4, 'Pocitos 303', true),
  ('Burger House', 'Hamburguesas gourmet', 'Fast Food', 4.3, 'Centro 404', true),
  ('Green Life', 'Comida saludable', 'Saludable', 4.5, 'Parque Rodó 505', true),
  ('El Italiano', 'Pastas frescas', 'Italiano', 4.6, 'Centro 606', false),
  ('Taco Loco', 'Tacos mexicanos', 'Mexicano', 4.1, 'Cordón 707', true),
  ('Café del Mar', 'Café y brunch', 'Café', 4.3, 'Pocitos 808', true),
  ('La Bodeguita', 'Comida casera', 'Tradicional', 4.0, 'Centro 909', false),
  ('Veggie World', 'Opciones veganas', 'Vegano', 4.7, 'Cordón 111', true),
  ('Don Asado', 'Parrilla uruguaya', 'Parrilla', 4.8, 'Centro 112', true),
  ('Pizza Express', 'Pizza rápida', 'Pizza', 3.9, 'Centro 113', true),
  ('Sakura', 'Sushi clásico', 'Japonés', 4.6, 'Pocitos 114', true),
  ('Burger City', 'Burgers grandes', 'Fast Food', 4.2, 'Centro 115', false),
  ('Healthy Bowl', 'Bowls saludables', 'Saludable', 4.4, 'Cordón 116', true),
  ('Roma Pasta', 'Comida italiana', 'Italiano', 4.5, 'Centro 117', true),
  ('Azteca', 'Comida mexicana', 'Mexicano', 4.3, 'Cordón 118', true),
  ('Coffee Lab', 'Especialidad café', 'Café', 4.7, 'Pocitos 119', true),
  ('Casa Abuela', 'Platos caseros', 'Tradicional', 4.1, 'Centro 120', false),
  ('Vegan Point', '100% vegano', 'Vegano', 4.6, 'Cordón 121', true),
  ('La Estancia', 'Carnes premium', 'Parrilla', 4.9, 'Centro 122', true),
  ('Napoli Pizza', 'Pizza napolitana', 'Pizza', 4.5, 'Centro 123', true),
  ('Tokyo Roll', 'Sushi moderno', 'Japonés', 4.3, 'Pocitos 124', false),
  ('Big Burger', 'Hamburguesas XXL', 'Fast Food', 4.0, 'Centro 125', true),
  ('Fit Food', 'Comida fit', 'Saludable', 4.2, 'Cordón 126', true),
  ('Trattoria', 'Pastas y vinos', 'Italiano', 4.7, 'Centro 127', true),
  ('El Mariachi', 'Mexicano picante', 'Mexicano', 4.1, 'Cordón 128', true),
  ('Café Central', 'Desayunos', 'Café', 4.0, 'Centro 129', true),
  ('La Cocina', 'Comida tradicional', 'Tradicional', 3.8, 'Centro 130', false),
  ('Veggie Green', 'Vegano moderno', 'Vegano', 4.5, 'Cordón 131', true),
  ('Asado House', 'Parrilla clásica', 'Parrilla', 4.4, 'Centro 132', true),
  ('Pizza Top', 'Pizza gourmet', 'Pizza', 4.6, 'Cordón 133', true),
  ('Sushi Pro', 'Alta cocina japonesa', 'Japonés', 4.8, 'Pocitos 134', true),
  ('Burger Club', 'Burgers premium', 'Fast Food', 4.5, 'Centro 135', true),
  ('Nutri Food', 'Comida sana', 'Saludable', 4.3, 'Cordón 136', true),
  ('Italia Mia', 'Recetas italianas', 'Italiano', 4.7, 'Centro 137', true),
  ('Taco King', 'Tacos variados', 'Mexicano', 4.2, 'Cordón 138', false),
  ('Café Urbano', 'Café moderno', 'Café', 4.4, 'Pocitos 139', true),
  ('Tradición', 'Recetas locales', 'Tradicional', 4.1, 'Centro 140', true),
  ('Vegan Style', 'Vegano creativo', 'Vegano', 4.6, 'Cordón 141', true),
  ('Parrilla Norte', 'Asado uruguayo', 'Parrilla', 4.7, 'Centro 142', true),
  ('Pizza Boom', 'Pizza crocante', 'Pizza', 4.2, 'Centro 143', true),
  ('Sushi Zen', 'Sushi tranquilo', 'Japonés', 4.5, 'Pocitos 144', true),
  ('Burger Spot', 'Hamburguesas simples', 'Fast Food', 3.9, 'Centro 145', true),
  ('Green Eat', 'Healthy food', 'Saludable', 4.4, 'Cordón 146', true),
  ('Bella Italia', 'Cocina italiana', 'Italiano', 4.8, 'Centro 147', true),
  ('Mex Food', 'Mexicano clásico', 'Mexicano', 4.0, 'Cordón 148', true),
  ('Café Express', 'Café rápido', 'Café', 3.9, 'Centro 149', false),
  ('Casa Criolla', 'Comida típica', 'Tradicional', 4.3, 'Centro 150', true),
  ('Vegan Mix', 'Opciones veganas', 'Vegano', 4.5, 'Cordón 151', true),
  ('El Fuego', 'Parrilla gourmet', 'Parrilla', 4.9, 'Centro 152', true),
  ('Pizza Max', 'Pizza abundante', 'Pizza', 4.1, 'Centro 153', true),
  ('Sushi Master', 'Sushi premium', 'Japonés', 4.7, 'Pocitos 154', true),
  ('Burger Grill', 'Burgers a la parrilla', 'Fast Food', 4.4, 'Centro 155', true),
  ('Healthy Life', 'Comida saludable', 'Saludable', 4.6, 'Cordón 156', true),
  ('Roma Food', 'Comida italiana', 'Italiano', 4.3, 'Centro 157', false),
  ('Taco Street', 'Street food mexicano', 'Mexicano', 4.2, 'Cordón 158', true),
  ('Café House', 'Café y tortas', 'Café', 4.5, 'Pocitos 159', true),
  ('Tradición Uy', 'Comida uruguaya', 'Tradicional', 4.4, 'Centro 160', true),
  ('Vegan House', 'Vegano completo', 'Vegano', 4.8, 'Cordón 161', true),
  ('Parrilla Sur', 'Asado tradicional', 'Parrilla', 4.3, 'Centro 162', true),
  ('Pizza Club', 'Pizza familiar', 'Pizza', 4.0, 'Centro 163', true),
  ('Sushi Time', 'Sushi rápido', 'Japonés', 4.2, 'Pocitos 164', true),
  ('Burger Time', 'Fast burgers', 'Fast Food', 3.8, 'Centro 165', false),
  ('Green Bowl', 'Bowls saludables', 'Saludable', 4.5, 'Cordón 166', true),
  ('Italia Express', 'Italiano rápido', 'Italiano', 4.1, 'Centro 167', true),
  ('Taco Express', 'Tacos rápidos', 'Mexicano', 3.9, 'Cordón 168', true),
  ('Café Simple', 'Café básico', 'Café', 3.7, 'Centro 169', true),
  ('Tradición Plus', 'Comida casera', 'Tradicional', 4.2, 'Centro 170', true),
  ('Vegan Fast', 'Vegano rápido', 'Vegano', 4.3, 'Cordón 171', true),
  ('Parrilla 10', 'Top carnes', 'Parrilla', 4.8, 'Centro 172', true),
  ('Pizza 10', 'Top pizza', 'Pizza', 4.7, 'Centro 173', true),
  ('Sushi 10', 'Top sushi', 'Japonés', 4.9, 'Pocitos 174', true),
  ('Burger 10', 'Top burgers', 'Fast Food', 4.6, 'Centro 175', true),
  ('Healthy 10', 'Top saludable', 'Saludable', 4.7, 'Cordón 176', true),
  ('Italia 10', 'Top italiano', 'Italiano', 4.8, 'Centro 177', true),
  ('Taco 10', 'Top mexicano', 'Mexicano', 4.5, 'Cordón 178', true),
  ('Café 10', 'Top café', 'Café', 4.6, 'Centro 179', true),
  ('Tradición 10', 'Top casero', 'Tradicional', 4.7, 'Centro 180', true),
  ('Vegan 10', 'Top vegano', 'Vegano', 4.9, 'Cordón 181', true);
    
    
    
    
    
    
    ;
