spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marketplace}
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:devpass}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/marketplace}
    user: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:devpass}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info